services:
  - type: web
    name: sunabaco-notifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GMAIL_ADDRESS
        value: あなたのGmailアドレス
      - key: GMAIL_APP_PASSWORD
        value: Gmailのアプリパスワード
      - key: TO_ADDRESS
        value: 送信先アドレス
